# Postgresql DB.

default: &default
  adapter: postgresql
  encodin: unicode
  pool: 10

development:
  <<: *default
  database: mageknight_api_development

test:
  <<: *default
  database: mageknight_api_test

production:
  <<: *default
  database: mageknight_api
